os: Visual Studio 2015

platform:
  - x64

services:
  - mysql

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

build_script:
  - SET
  - CD
  - cd ..
  - CD
  - git clone https://github.com/HowardHinnant/date
  - git clone https://github.com/rbock/sqlpp11
  - cd sqlpp11
  - git checkout develop
  - cd ..
  - cd sqlpp11-connector-mysql
  - CD
  - echo %configuration%
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -DCMAKE_CXX_FLAGS="/EHsc /wd4503"
  - cmake --build . --config %configuration%
  - ctest . --build-config %configuration%

