os: Visual Studio 2015

platform:
  - x64

services:
  - mysql

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

build_script:
  - cmake --version
  - SET
  - CD
  - cd ..
  - CD
  - git clone https://github.com/MariaDB/mariadb-connector-c
  - cd mariadb-connector-c
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_FLAGS="/EHsc /wd4503" -DCMAKE_GENERATOR_PLATFORM=x64
  - cmake --build . --config %configuration%
  - cmake --build . --config %configuration% --target install
  - CD ..
  - CD ..
  - CD
  - git clone https://github.com/HowardHinnant/date
  - git clone https://github.com/rbock/sqlpp11
  - cd sqlpp11-connector-mysql
  - CD
  - echo %configuration%
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_FLAGS="/EHsc /wd4503" -DCMAKE_GENERATOR_PLATFORM=x64
  - cmake --build . --config %configuration%
  - ctest . --build-config %configuration%

